### ISSUE TITLE
Wrong windows library name

### ISSUE THREAD

**Issue by falkTX** [jackaudio/pyjacklib#2]
From https://github.com/jackaudio/pyjacklib/blob/v0.1.1/jacklib/api.py#L51

name should be libjack64.dll if win64, and libjack.dll if win32

**Comment by SpotlightKid** [comment]
What about the `cygwin` case?

**Comment by falkTX** [comment]
no ideas, I have never used cygwin. the detection should be for 64 vs 32bit platform perhaps. though that has always been complicated in python from my experience. perhaps we can check the pointer size?

**Comment by SpotlightKid** [comment]
[According to SO](https://stackoverflow.com/a/12578715), this should work (note that "win64" is not actually a possible value of `sys.platform`):

```py
# https://stackoverflow.com/a/12578715
def _is_windows_64bit():
    if 'PROCESSOR_ARCHITEW6432' in environ:
        return True
    return environ['PROCESSOR_ARCHITECTURE'].endswith('64')

try:
    if platform == "darwin":
        _libname = "libjack.dylib"
    elif platform in ("win32", "cygwin"):
        if _is_windows_64bit:
            _libname = "libjack64.dll"
        else:
            _libname = "libjack.dll"
    else:
        _libname = "libjack.so.0"

    jlib = cdll.LoadLibrary(_libname)
except OSError:
    raise ImportError("JACK is not available in this system")
```

**Comment by falkTX** [comment]
So 32bit python on 64bit windows will load 32bit jack, that being libjack.dll
