### ISSUE TITLE
free_description call assumes function pointer is valid

### ISSUE THREAD

**Issue by falkTX** [jackaudio/pyjacklib#6]
There is a try/catch for jack_free_description but it is not used

**Comment by SpotlightKid** [comment]
I can put an `if jlib.jack_free_description:` in `free_description`, but I think it's a fix to a theoretical problem only.

`jack_free_description` is only used in the metadata API functions. If those are available, `jack_free_description` should be too, no? If they are not available, you wouldn't be able to get a `jack_description_t` pointer in the first place, so calling  `free_description` wouldn't make much sense.

Correct me, if I'm wrong.
